spring:
  application:
    name: connect-luck

  profiles:
    default: local

jwt:
  secret: ${JWT_SECRET:this-is-a-secret-key-and-it-should-be-kept-secure}
  issuer: ${JWT_ISSUER:connect-luck}
  expiry: ${JWT_EXPIRATION:3600000}


springdoc:
  swagger-ui:
    tags-sorter: alpha

imgbb:
  key: ${IMGBB_API_KEY}

data.go.kr:
  key: ${DATA_GO_KR_API_KEY:data.go.kr-api-key}

api-key:
  kakao: ${KAKAO_API_KEY:kakao-api-key}
