spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: embedded
      encoding: utf-8

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB
