spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/connectluck
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always
      encoding: utf-8

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true


jwt:
  secret: ${JWT_SECRET:this-is-a-secret-key-and-it-should-be-kept-secure}
  issuer: ${JWT_ISSUER:connect-luck}
  expiry: ${JWT_EXPIRATION:3600000}


springdoc:
  swagger-ui:
    tags-sorter: alpha

imgbb:
  key: ${IMGBB_API_KEY}

api-key:
  kakao: ${KAKAO_API_KEY:kakao-api-key}
