spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: embedded
      encoding: utf-8

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  forward-headers-strategy: framework

### Uncomment the following block to enable HTTPS and HTTP/2
#  port: 8443
#
#  http2:
#    enabled: true
#
#  ssl:
#    enabled: true
#    certificate-private-key: "classpath:privkey.pem"
#    certificate: "classpath:fullchain.pem"

jwt:
  secret: ${JWT_SECRET:this-is-a-secret-key-and-it-should-be-kept-secure}
  issuer: ${JWT_ISSUER:connect-luck}
  expiry: ${JWT_EXPIRATION:3600000}


springdoc:
  swagger-ui:
    tags-sorter: alpha

imgbb:
  key: ${IMGBB_API_KEY}

api-key:
  kakao: ${KAKAO_API_KEY:kakao-api-key}
